const categories = [
  {
    name: 'Cultural Heritage',
    slug: 'cultural-heritage',
    description: 'Ancient kingdoms, UNESCO World Heritage monuments, sacred temples, and timeless ruins.',
    icon: 'Landmark',
    image: 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1000&q=80',
    destinationCount: 5,
  },
  {
    name: 'Beaches & Coastal',
    slug: 'beaches-coastal',
    description: 'Pristine golden sands, turquoise ocean swells, surfing sanctuaries, and tranquil marine life.',
    icon: 'Palmtree',
    image: 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1000&q=80',
    destinationCount: 6,
  },
  {
    name: 'Hill Country & Tea',
    slug: 'hill-country-tea',
    description: 'Misty cloud forests, emerald tea estates, cascading waterfalls, and cool mountain retreats.',
    icon: 'Mountain',
    image: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1000&q=80',
    destinationCount: 4,
  },
  {
    name: 'Wildlife & Safari',
    slug: 'wildlife-safari',
    description: 'Encounter roaming Sri Lankan leopards, wild elephant herds, sloth bears, and endemic birds.',
    icon: 'PawPrint',
    image: 'https://images.unsplash.com/photo-1564760055775-d63b17a55c44?auto=format&fit=crop&w=1000&q=80',
    destinationCount: 3,
  },
  {
    name: 'Nature & Adventure',
    slug: 'nature-adventure',
    description: 'White water rapids, highland trekking peaks, hidden rainforests, and adrenaline rushes.',
    icon: 'Compass',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
    destinationCount: 3,
  },
  {
    name: 'Urban & Modern',
    slug: 'urban-modern',
    description: 'Cosmopolitan dining, colonial architecture, vibrant street markets, and luxury coastal skylines.',
    icon: 'Building2',
    image: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1000&q=80',
    destinationCount: 1,
  },
];

const destinations = [
  {
    name: 'Sigiriya',
    slug: 'sigiriya',
    province: 'Central',
    district: 'Matale',
    location: { latitude: 7.957, longitude: 80.7603 },
    category: 'Cultural Heritage',
    shortDescription: 'The iconic 5th-century ancient fortress and palace ruin perched atop a 200m sheer granite rock.',
    description: 'Sigiriya, also known as the Lion Rock, is a UNESCO World Heritage site and an ancient royal fortress. Built during the reign of King Kashyapa (477-495 CE), it features marvelous water gardens, world-famous fresco paintings, the Mirror Wall with ancient graffiti, and gigantic carved lion paws guarding the final staircase to the palace plateau.',
    images: [
      'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 22000,
    recommendedDuration: 1,
    bestMonths: ['January', 'February', 'March', 'June', 'July', 'August'],
    activities: [
      { name: 'Climb Lion Rock', description: 'Ascend the 1,200 steps past ancient frescoes to the summit ruins.', estimatedCost: 10500, duration: '3 hours' },
      { name: 'Pidurangala Sunrise Hike', description: 'Panoramic morning trek overlooking Sigiriya Rock.', estimatedCost: 1000, duration: '2 hours' },
      { name: 'Village Bull-Cart & Boat Safari', description: 'Traditional rural lake catamaran ride and authentic village cooking.', estimatedCost: 4500, duration: '2.5 hours' },
    ],
    difficulty: 'Moderate',
    popularityScore: 98,
    averageRating: 4.9,
    reviewCount: 342,
    entranceFee: { local: 100, foreign: 11000 },
    tags: ['Culture', 'History', 'Photography', 'Hiking', 'Adventure'],
    nearbyDestinations: [
      { name: 'Dambulla', distanceKm: 24 },
      { name: 'Polonnaruwa', distanceKm: 58 },
      { name: 'Kandy', distanceKm: 90 },
    ],
    transportationInfo: { trainAvailable: false, busAvailable: true, driveTimeFromColombo: '3.5 - 4 hours' },
  },
  {
    name: 'Ella',
    slug: 'ella',
    province: 'Uva',
    district: 'Badulla',
    location: { latitude: 6.8667, longitude: 81.0466 },
    category: 'Hill Country & Tea',
    shortDescription: 'Charming mountain town famous for Nine Arch Bridge, hiking peaks, lush tea terraces, and laid-back vibes.',
    description: 'Ella is a picturesque mountain hamlet in Sri Lanka’s highlands surrounded by rolling green hills, cloud-kissed peaks, and sprawling tea plantations. Key highlights include walking along the iconic colonial Demodara Nine Arch Bridge, trekking Little Adam’s Peak, hiking Ella Rock, and swimming beneath Ravana Falls.',
    images: [
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 18000,
    recommendedDuration: 2,
    bestMonths: ['January', 'February', 'March', 'April', 'July', 'August', 'September'],
    activities: [
      { name: 'Nine Arch Bridge Crossing', description: 'Watch the scenic blue train rumble across the colonial railway bridge.', estimatedCost: 0, duration: '2 hours' },
      { name: 'Little Adam’s Peak Hike', description: 'Easy summit walk offering sweeping vistas across Ella Gap.', estimatedCost: 0, duration: '2 hours' },
      { name: 'Ravana Pool & Waterfalls', description: 'Marvel at cascading waters steeped in the Ramayana epic.', estimatedCost: 500, duration: '1.5 hours' },
      { name: 'Tea Factory Tasting Tour', description: 'Learn how world-renowned Ceylon tea is picked, rolled, and brewed.', estimatedCost: 1500, duration: '1.5 hours' },
    ],
    difficulty: 'Moderate',
    popularityScore: 96,
    averageRating: 4.8,
    reviewCount: 289,
    entranceFee: { local: 0, foreign: 0 },
    tags: ['Hiking', 'Nature', 'Tea', 'Waterfalls', 'Photography', 'Adventure'],
    nearbyDestinations: [
      { name: 'Nuwara Eliya', distanceKm: 55 },
      { name: 'Yala', distanceKm: 88 },
      { name: 'Kandy', distanceKm: 135 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '5 - 6 hours (or scenic train)' },
  },
  {
    name: 'Kandy',
    slug: 'kandy',
    province: 'Central',
    district: 'Kandy',
    location: { latitude: 7.2906, longitude: 80.6337 },
    category: 'Cultural Heritage',
    shortDescription: 'The hill capital of Sri Lanka and home to the sacred Temple of the Sacred Tooth Relic.',
    description: 'Nestled amidst mist-clad forested hills, Kandy was the last royal capital of independent Sri Lanka. The city surrounds an artificial lake created in 1807 and houses Sri Dalada Maligawa (Temple of the Sacred Tooth Relic), one of Buddhism’s most sacred shrines. It is also famous for the lush Royal Botanical Gardens of Peradeniya and traditional Kandyan dance performances.',
    images: [
      'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 20000,
    recommendedDuration: 2,
    bestMonths: ['January', 'February', 'March', 'July', 'August', 'December'],
    activities: [
      { name: 'Temple of the Tooth Relic (Dalada Maligawa)', description: 'Participate in the sacred evening Thevava ceremony.', estimatedCost: 2000, duration: '2 hours' },
      { name: 'Peradeniya Royal Botanical Gardens', description: 'Stroll beneath towering palm avenues and giant Javan fig trees.', estimatedCost: 3000, duration: '3 hours' },
      { name: 'Kandyan Cultural Dance Show', description: 'Energetic traditional drumming, acrobatic dancing, and fire-walking.', estimatedCost: 2500, duration: '1 hour' },
    ],
    difficulty: 'Easy',
    popularityScore: 94,
    averageRating: 4.7,
    reviewCount: 310,
    entranceFee: { local: 0, foreign: 2000 },
    tags: ['Culture', 'History', 'Food', 'Shopping', 'Photography'],
    nearbyDestinations: [
      { name: 'Nuwara Eliya', distanceKm: 76 },
      { name: 'Sigiriya', distanceKm: 90 },
      { name: 'Colombo', distanceKm: 115 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '3 hours' },
  },
  {
    name: 'Galle Fort',
    slug: 'galle-fort',
    province: 'Southern',
    district: 'Galle',
    location: { latitude: 6.0328, longitude: 80.217 },
    category: 'Cultural Heritage',
    shortDescription: 'Magnificent 17th-century coastal fortress built by Portuguese and Dutch colonizers on the Indian Ocean.',
    description: 'Galle Fort is an extraordinary living UNESCO World Heritage monument. Enclosed by massive sea ramparts, its cobblestone streets are filled with Dutch-colonial mansions, boutique gem jewelers, artisanal gelato shops, historic churches, and the iconic white Galle Lighthouse overlooking the roaring surf.',
    images: [
      'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 25000,
    recommendedDuration: 1,
    bestMonths: ['November', 'December', 'January', 'February', 'March', 'April'],
    activities: [
      { name: 'Ramparts Sunset Walk', description: 'Stroll the fortress walls past the Dutch bastion to the lighthouse at dusk.', estimatedCost: 0, duration: '2 hours' },
      { name: 'Dutch Reformed Church & Museum', description: 'Explore colonial gravestones, maritime artifacts, and architecture.', estimatedCost: 500, duration: '1.5 hours' },
      { name: 'Boutique Shopping & Street Dining', description: 'Browse handmade lace, sapphires, spices, and contemporary cafes.', estimatedCost: 5000, duration: '2 hours' },
    ],
    difficulty: 'Easy',
    popularityScore: 95,
    averageRating: 4.8,
    reviewCount: 275,
    entranceFee: { local: 0, foreign: 0 },
    tags: ['Culture', 'History', 'Photography', 'Shopping', 'Food', 'Beaches'],
    nearbyDestinations: [
      { name: 'Unawatuna', distanceKm: 6 },
      { name: 'Mirissa', distanceKm: 34 },
      { name: 'Bentota', distanceKm: 55 },
      { name: 'Colombo', distanceKm: 120 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '1.5 - 2 hours via expressway' },
  },
  {
    name: 'Mirissa',
    slug: 'mirissa',
    province: 'Southern',
    district: 'Matara',
    location: { latitude: 5.9483, longitude: 80.4578 },
    category: 'Beaches & Coastal',
    shortDescription: 'Crescent-shaped golden beach celebrated for blue whale watching, coconut tree hills, and vibrant nightlife.',
    description: 'Mirissa is one of the premier beach paradises on the southern coastline. Renowned globally as one of the best locations to spot majestic blue whales and playful dolphins, Mirissa also features the Instagram-famous Coconut Tree Hill, Secret Beach, relaxed surf breaks, and fresh seafood barbecue on the sand under candlelit lantern tables.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 20000,
    recommendedDuration: 2,
    bestMonths: ['November', 'December', 'January', 'February', 'March', 'April'],
    activities: [
      { name: 'Blue Whale & Dolphin Watching Safari', description: 'Morning boat cruise into deep continental shelf waters.', estimatedCost: 16000, duration: '4 hours' },
      { name: 'Coconut Tree Hill Photography', description: 'Visit the headland overlooking turquoise bays fringed with bent palms.', estimatedCost: 0, duration: '1 hour' },
      { name: 'Surfing at Mirissa Point', description: 'Catch right-hand point reef waves suitable for intermediate surfers.', estimatedCost: 3500, duration: '2 hours' },
    ],
    difficulty: 'Easy',
    popularityScore: 93,
    averageRating: 4.7,
    reviewCount: 260,
    entranceFee: { local: 0, foreign: 0 },
    tags: ['Beaches', 'Wildlife', 'Surfing', 'Photography', 'Food'],
    nearbyDestinations: [
      { name: 'Galle Fort', distanceKm: 34 },
      { name: 'Tangalle', distanceKm: 42 },
      { name: 'Yala', distanceKm: 110 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '2.5 hours' },
  },
  {
    name: 'Nuwara Eliya',
    slug: 'nuwara-eliya',
    province: 'Central',
    district: 'Nuwara Eliya',
    location: { latitude: 6.9497, longitude: 80.7891 },
    category: 'Hill Country & Tea',
    shortDescription: '“Little England” of Sri Lanka, famed for cool mountain climates, tea factories, and colonial architecture.',
    description: 'Sitting at 1,868 meters above sea level, Nuwara Eliya offers crisp mountain breezes, manicured rose gardens, Tudor-style cottages, and vast estates producing premier high-grown Ceylon tea. Attractions include serene Lake Gregory, Victoria Park, the red-brick Post Office, and Pedro Tea Estate.',
    images: [
      'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 24000,
    recommendedDuration: 2,
    bestMonths: ['February', 'March', 'April', 'May'],
    activities: [
      { name: 'Pedro Tea Estate Tour', description: 'Walk through lush terraces and sample freshly processed green and black teas.', estimatedCost: 1000, duration: '1.5 hours' },
      { name: 'Lake Gregory Boating & Cycling', description: 'Enjoy swan pedal boats, jet skis, and horse riding along the shore.', estimatedCost: 2000, duration: '2 hours' },
      { name: 'Lover’s Leap Waterfall Trek', description: 'Scenic highland walk leading to a breathtaking cascade.', estimatedCost: 0, duration: '2 hours' },
    ],
    difficulty: 'Easy',
    popularityScore: 91,
    averageRating: 4.6,
    reviewCount: 220,
    entranceFee: { local: 100, foreign: 500 },
    tags: ['Tea', 'Nature', 'Waterfalls', 'Photography', 'Food'],
    nearbyDestinations: [
      { name: 'Horton Plains', distanceKm: 28 },
      { name: 'Ella', distanceKm: 55 },
      { name: 'Kandy', distanceKm: 76 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '4.5 hours' },
  },
  {
    name: 'Yala National Park',
    slug: 'yala-national-park',
    province: 'Southern',
    district: 'Hambantota',
    location: { latitude: 6.3687, longitude: 81.5204 },
    category: 'Wildlife & Safari',
    shortDescription: 'World-famous wildlife reserve having the highest leopard density on earth, elephants, and crocodiles.',
    description: 'Yala National Park is Sri Lanka’s premier wildlife safari sanctuary. Its vast landscape encompasses scrub jungle, open plains, brackish lagoons, and rocky granite monoliths facing the Indian Ocean. Yala Block 1 boasts the highest recorded density of leopards (Panthera pardus kotiya) globally, along with herds of Asian elephants, sloth bears, spotted deer, and water monitors.',
    images: [
      'https://images.unsplash.com/photo-1564760055775-d63b17a55c44?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 35000,
    recommendedDuration: 1,
    bestMonths: ['February', 'March', 'April', 'May', 'June', 'July'],
    activities: [
      { name: 'Full-Day 4x4 Leopard Safari', description: 'Open-top safari jeep guided expedition through Block 1 and 2.', estimatedCost: 28000, duration: '6 hours' },
      { name: 'Bird Watching at Buthawa Lagoon', description: 'Spot painted storks, pelicans, flamingos, and sea eagles.', estimatedCost: 0, duration: '2 hours' },
    ],
    difficulty: 'Moderate',
    popularityScore: 97,
    averageRating: 4.8,
    reviewCount: 380,
    entranceFee: { local: 250, foreign: 12000 },
    tags: ['Wildlife', 'Adventure', 'Photography', 'Nature'],
    nearbyDestinations: [
      { name: 'Udawalawe', distanceKm: 85 },
      { name: 'Ella', distanceKm: 88 },
      { name: 'Mirissa', distanceKm: 110 },
    ],
    transportationInfo: { trainAvailable: false, busAvailable: true, driveTimeFromColombo: '4.5 hours via Southern Expressway' },
  },
  {
    name: 'Arugam Bay',
    slug: 'arugam-bay',
    province: 'Eastern',
    district: 'Ampara',
    location: { latitude: 6.8419, longitude: 81.8344 },
    category: 'Beaches & Coastal',
    shortDescription: 'World-renowned surfing mecca with legendary right-hand point breaks, lagoons, and bohemian charm.',
    description: 'Arugam Bay is an internationally celebrated surfing paradise on Sri Lanka’s sunny eastern coast. Known for consistent, long peeling right-hand point waves at Main Point and Whiskey Point, Arugam Bay also offers serene mangrove kayak safaris at Pottuvil Lagoon, yoga retreats, and beachside bonfire dining.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 19000,
    recommendedDuration: 2,
    bestMonths: ['May', 'June', 'July', 'August', 'September', 'October'],
    activities: [
      { name: 'Point Break Surfing', description: 'Catch world-class right-hand barrel waves at Main Point.', estimatedCost: 4000, duration: '3 hours' },
      { name: 'Pottuvil Lagoon Eco-Canoeing', description: 'Paddle through quiet mangroves spotting elephants and kingfishers.', estimatedCost: 3500, duration: '2.5 hours' },
      { name: 'Kudumbigala Monastery Hike', description: 'Ancient hermit monastery atop rock outcrops with jungle vistas.', estimatedCost: 0, duration: '2 hours' },
    ],
    difficulty: 'Moderate',
    popularityScore: 90,
    averageRating: 4.7,
    reviewCount: 195,
    entranceFee: { local: 0, foreign: 0 },
    tags: ['Beaches', 'Surfing', 'Adventure', 'Photography', 'Wildlife'],
    nearbyDestinations: [
      { name: 'Yala', distanceKm: 115 },
      { name: 'Ella', distanceKm: 130 },
      { name: 'Pasikudah', distanceKm: 140 },
    ],
    transportationInfo: { trainAvailable: false, busAvailable: true, driveTimeFromColombo: '6 - 7 hours' },
  },
  {
    name: 'Anuradhapura',
    slug: 'anuradhapura',
    province: 'North Central',
    district: 'Anuradhapura',
    location: { latitude: 8.3114, longitude: 80.4037 },
    category: 'Cultural Heritage',
    shortDescription: 'Sprawling sacred capital of ancient Sri Lanka, home to giant stupas and the oldest documented tree.',
    description: 'Anuradhapura served as the political and spiritual heart of Sri Lanka for over thirteen centuries. This ancient royal capital features colossally massive brick stupas like Ruwanwelisaya and Jetavanaramaya, the sacred Jaya Sri Maha Bodhi (a sapling of the historical Bodhi tree in India), intricate moonstones, and stone swimming pools carved by monks.',
    images: [
      'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 19000,
    recommendedDuration: 2,
    bestMonths: ['January', 'February', 'March', 'June', 'July', 'August', 'September'],
    activities: [
      { name: 'Ruwanwelisaya White Stupa Pilgrimage', description: 'Experience the spiritual aura around the 103-meter ancient shrine.', estimatedCost: 0, duration: '2 hours' },
      { name: 'Jaya Sri Maha Bodhi Homage', description: 'Visit the 2,300-year-old sacred fig tree.', estimatedCost: 500, duration: '1 hour' },
      { name: 'Cycling the Ancient Monastic Ruins', description: 'Pedal between monasteries, twin ponds (Kuttam Pokuna), and Samadhi statues.', estimatedCost: 1500, duration: '3.5 hours' },
    ],
    difficulty: 'Easy',
    popularityScore: 89,
    averageRating: 4.7,
    reviewCount: 210,
    entranceFee: { local: 0, foreign: 8500 },
    tags: ['Culture', 'History', 'Photography'],
    nearbyDestinations: [
      { name: 'Sigiriya', distanceKm: 75 },
      { name: 'Polonnaruwa', distanceKm: 104 },
      { name: 'Jaffna', distanceKm: 195 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '4 hours' },
  },
  {
    name: 'Trincomalee',
    slug: 'trincomalee',
    province: 'Eastern',
    district: 'Trincomalee',
    location: { latitude: 8.5874, longitude: 81.2152 },
    category: 'Beaches & Coastal',
    shortDescription: 'Spectacular deep-water harbor, Nilaveli coral reef snorkeling, and sacred cliffside Koneswaram Temple.',
    description: 'Trincomalee is an eastern coastal jewel featuring one of the world’s finest natural harbors. Highlights include the vibrant clifftop Koneswaram Hindu Temple with its dramatic Swami Rock drop, the white powder beaches of Nilaveli, and Pigeon Island National Park, where travelers snorkel with blacktip reef sharks and sea turtles.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 22000,
    recommendedDuration: 2,
    bestMonths: ['April', 'May', 'June', 'July', 'August', 'September', 'October'],
    activities: [
      { name: 'Pigeon Island Marine Snorkeling', description: 'Swim through shallow coral reefs with harmless reef sharks and sea turtles.', estimatedCost: 12000, duration: '3.5 hours' },
      { name: 'Koneswaram Temple & Swami Rock', description: 'Explore the golden Shiva shrine perched above azure waves.', estimatedCost: 0, duration: '1.5 hours' },
      { name: 'Nilaveli Beach Relaxation', description: 'Unwind on pristine uncrowded sands and calm swimming waters.', estimatedCost: 0, duration: '3 hours' },
    ],
    difficulty: 'Easy',
    popularityScore: 91,
    averageRating: 4.8,
    reviewCount: 235,
    entranceFee: { local: 100, foreign: 6000 },
    tags: ['Beaches', 'Culture', 'Wildlife', 'Adventure', 'Photography'],
    nearbyDestinations: [
      { name: 'Pasikudah', distanceKm: 110 },
      { name: 'Anuradhapura', distanceKm: 110 },
      { name: 'Sigiriya', distanceKm: 100 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '5 hours' },
  },
  {
    name: 'Bentota',
    slug: 'bentota',
    province: 'Southern',
    district: 'Galle',
    location: { latitude: 6.4259, longitude: 79.9959 },
    category: 'Beaches & Coastal',
    shortDescription: 'Golden beach paradise famed for water sports, luxury beachfront resorts, and Madu River boat safaris.',
    description: 'Bentota is Sri Lanka’s premier water sports haven, located where the gentle Bentota River flows into the Indian Ocean. Visitors revel in jet skiing, windsurfing, banana boating, exploring Geoffrey Bawa’s Lunuganga country estate, and touring the mangrove wetlands of the Madu Ganga.',
    images: [
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 26000,
    recommendedDuration: 1,
    bestMonths: ['November', 'December', 'January', 'February', 'March', 'April'],
    activities: [
      { name: 'Bentota River Water Sports', description: 'Jet ski, wakeboard, and tube across calm river waters.', estimatedCost: 7500, duration: '2 hours' },
      { name: 'Madu Ganga Mangrove River Safari', description: 'Boat cruise through 64 islands, cinnamon peeling demonstrations, and fish therapy.', estimatedCost: 4500, duration: '2 hours' },
      { name: 'Kosgoda Sea Turtle Conservation Project', description: 'Observe baby hatchlings and injured sea turtle rehabilitation.', estimatedCost: 1500, duration: '1 hour' },
    ],
    difficulty: 'Easy',
    popularityScore: 88,
    averageRating: 4.6,
    reviewCount: 190,
    entranceFee: { local: 0, foreign: 0 },
    tags: ['Beaches', 'Adventure', 'Nature', 'Photography'],
    nearbyDestinations: [
      { name: 'Galle Fort', distanceKm: 55 },
      { name: 'Colombo', distanceKm: 65 },
      { name: 'Mirissa', distanceKm: 85 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '1 hour via Southern Expressway' },
  },
  {
    name: 'Colombo',
    slug: 'colombo',
    province: 'Western',
    district: 'Colombo',
    location: { latitude: 6.9271, longitude: 79.8612 },
    category: 'Urban & Modern',
    shortDescription: 'The dynamic commercial capital combining colonial landmarks, modern skyscrapers, street food, and oceanside parks.',
    description: 'Colombo is Sri Lanka’s vibrant seaside metropolis. A captivating blend of Portuguese, Dutch, and British colonial history with gleaming high-rises, Colombo offers world-class dining, bustling open markets in Pettah, the serene Gangaramaya Buddhist Temple on Beira Lake, and picturesque sunset strolls along Galle Face Green.',
    images: [
      'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 25000,
    recommendedDuration: 1,
    bestMonths: ['January', 'February', 'March', 'July', 'August', 'September', 'December'],
    activities: [
      { name: 'Galle Face Green Sunset & Street Food', description: 'Savor crispy isso vade (prawn fritters) and watch ocean kites soar.', estimatedCost: 1500, duration: '2 hours' },
      { name: 'Gangaramaya & Seema Malaka Temples', description: 'Marvel at eclectic antique collections and tranquil floating pavilions.', estimatedCost: 500, duration: '1.5 hours' },
      { name: 'Pettah Bazaars & Red Mosque Walking Tour', description: 'Navigate colorful wholesale spice lanes and photograph Jami Ul-Alfar Mosque.', estimatedCost: 0, duration: '2.5 hours' },
    ],
    difficulty: 'Easy',
    popularityScore: 92,
    averageRating: 4.5,
    reviewCount: 320,
    entranceFee: { local: 0, foreign: 500 },
    tags: ['Food', 'Shopping', 'Culture', 'History', 'Photography'],
    nearbyDestinations: [
      { name: 'Negombo', distanceKm: 35 },
      { name: 'Bentota', distanceKm: 65 },
      { name: 'Kandy', distanceKm: 115 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '0 hours (Starting Hub)' },
  },
  {
    name: 'Horton Plains National Park',
    slug: 'horton-plains',
    province: 'Central',
    district: 'Nuwara Eliya',
    location: { latitude: 6.8028, longitude: 80.803 },
    category: 'Nature & Adventure',
    shortDescription: 'High-altitude windswept plateau leading to the dramatic 880-meter sheer precipice of World’s End.',
    description: 'Horton Plains is a silent, mist-shrouded montane plateau perched above 2,100 meters. The 9-kilometer loop trail meanders across wild moorlands, dwarf cloud forests, and ends at World’s End—a staggering vertical drop plunging 880 meters straight down into tea plantations below, followed by picturesque Baker’s Falls.',
    images: [
      'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 26000,
    recommendedDuration: 1,
    bestMonths: ['January', 'February', 'March'],
    activities: [
      { name: 'World’s End Early Morning Trek', description: 'Reach the cliff edge before 9 AM before the white cloud bank rolls in.', estimatedCost: 0, duration: '4 hours' },
      { name: 'Baker’s Falls Scenic Cascade', description: 'Descend to view the powerful highland waterfall named after Sir Samuel Baker.', estimatedCost: 0, duration: '1 hour' },
      { name: 'Spot Sambar Deer & Horned Lizards', description: 'Encounter Sri Lanka’s majestic highland fauna grazing in peace.', estimatedCost: 0, duration: '1 hour' },
    ],
    difficulty: 'Moderate',
    popularityScore: 92,
    averageRating: 4.8,
    reviewCount: 240,
    entranceFee: { local: 250, foreign: 10000 },
    tags: ['Hiking', 'Nature', 'Waterfalls', 'Photography', 'Adventure'],
    nearbyDestinations: [
      { name: 'Nuwara Eliya', distanceKm: 28 },
      { name: 'Ella', distanceKm: 55 },
      { name: 'Kandy', distanceKm: 100 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: false, driveTimeFromColombo: '5 hours' },
  },
  {
    name: 'Udawalawe National Park',
    slug: 'udawalawe',
    province: 'Sabaragamuwa',
    district: 'Ratnapura',
    location: { latitude: 6.4746, longitude: 80.8987 },
    category: 'Wildlife & Safari',
    shortDescription: 'One of the best places in Asia to see wild elephants up close roaming open savanna plains.',
    description: 'Surrounding the massive Udawalawe Reservoir, this park offers landscapes reminiscent of an African savanna. Home to over 500 wild Asian elephants, visitors are virtually guaranteed multiple close encounters with herds, playful calves, water buffalo, jackals, crocodiles, and crested serpent eagles.',
    images: [
      'https://images.unsplash.com/photo-1564760055775-d63b17a55c44?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 28000,
    recommendedDuration: 1,
    bestMonths: ['January', 'February', 'March', 'April', 'May', 'September', 'October'],
    activities: [
      { name: 'Open Jeep Elephant Safari', description: 'Safari drive through the reservoir banks witnessing elephant families bathing.', estimatedCost: 18000, duration: '3.5 hours' },
      { name: 'Elephant Transit Home Feeding Session', description: 'Watch rehabilitated orphaned baby elephants receive milk bottles.', estimatedCost: 1000, duration: '1 hour' },
    ],
    difficulty: 'Easy',
    popularityScore: 93,
    averageRating: 4.8,
    reviewCount: 295,
    entranceFee: { local: 200, foreign: 9000 },
    tags: ['Wildlife', 'Nature', 'Photography', 'Adventure'],
    nearbyDestinations: [
      { name: 'Ella', distanceKm: 65 },
      { name: 'Yala', distanceKm: 85 },
      { name: 'Mirissa', distanceKm: 95 },
    ],
    transportationInfo: { trainAvailable: false, busAvailable: true, driveTimeFromColombo: '3.5 hours' },
  },
  {
    name: 'Jaffna',
    slug: 'jaffna',
    province: 'Northern',
    district: 'Jaffna',
    location: { latitude: 9.6615, longitude: 80.0255 },
    category: 'Cultural Heritage',
    shortDescription: 'The cultural capital of the Northern Province, celebrated for Dravidian temples, crab curry, and island life.',
    description: 'Located in the northern tip of Sri Lanka, Jaffna possesses a unique Hindu-Tamil cultural identity. Renowned for the golden Nallur Kandaswamy Kovil, the expansive star-shaped Dutch Jaffna Fort, spicy Jaffna crab curry, sweet palmyra fruits, and ferry trips to Delft Island where wild ponies roam.',
    images: [
      'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 20000,
    recommendedDuration: 2,
    bestMonths: ['January', 'February', 'March', 'April', 'June', 'July', 'August', 'September'],
    activities: [
      { name: 'Nallur Kandaswamy Temple Puja', description: 'Witness traditional Hindu temple ceremonies with ringing bronze bells.', estimatedCost: 0, duration: '2 hours' },
      { name: 'Delft Island Ferry Expedition', description: 'Cruise across Palk Strait to discover coral walls and wild ponies.', estimatedCost: 2000, duration: '5 hours' },
      { name: 'Jaffna Crab Curry Feast', description: 'Taste legendary fiery northern seafood seasoned with roasted spices.', estimatedCost: 4500, duration: '1.5 hours' },
    ],
    difficulty: 'Moderate',
    popularityScore: 86,
    averageRating: 4.7,
    reviewCount: 165,
    entranceFee: { local: 0, foreign: 0 },
    tags: ['Culture', 'History', 'Food', 'Photography'],
    nearbyDestinations: [
      { name: 'Anuradhapura', distanceKm: 195 },
      { name: 'Trincomalee', distanceKm: 235 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '6.5 - 7 hours (or Yal Devi express train)' },
  },
  {
    name: 'Polonnaruwa',
    slug: 'polonnaruwa',
    province: 'North Central',
    district: 'Polonnaruwa',
    location: { latitude: 7.9403, longitude: 81.0188 },
    category: 'Cultural Heritage',
    shortDescription: 'The magnificent medieval royal capital featuring the monumental rock-carved Buddha statues of Gal Vihara.',
    description: 'Polonnaruwa was the glorious capital of Sri Lanka from the 11th to 13th centuries. Highlights include the royal palace of King Parakramabahu I, the Quadrangle (Dalada Maluwa), and Gal Vihara—a masterwork of ancient sculpture featuring four serene Buddha statues carved from a single granite slab.',
    images: [
      'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 20000,
    recommendedDuration: 1,
    bestMonths: ['January', 'February', 'March', 'June', 'July', 'August'],
    activities: [
      { name: 'Gal Vihara Granite Sculptures', description: 'Marvel at the 14-meter reclining Buddha statue carved from rock.', estimatedCost: 0, duration: '2 hours' },
      { name: 'Ancient Royal Palace & Quadrangle Tour', description: 'Explore seven-story palace ruins and round Vatadage shrine.', estimatedCost: 0, duration: '3 hours' },
      { name: 'Bicycle Tour around Parakrama Samudra', description: 'Cycle across the sea-like ancient reservoir dam.', estimatedCost: 1500, duration: '2 hours' },
    ],
    difficulty: 'Easy',
    popularityScore: 89,
    averageRating: 4.8,
    reviewCount: 205,
    entranceFee: { local: 0, foreign: 8500 },
    tags: ['Culture', 'History', 'Photography'],
    nearbyDestinations: [
      { name: 'Sigiriya', distanceKm: 58 },
      { name: 'Anuradhapura', distanceKm: 104 },
      { name: 'Kandy', distanceKm: 135 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '4.5 hours' },
  },
  {
    name: 'Dambulla',
    slug: 'dambulla',
    province: 'Central',
    district: 'Matale',
    location: { latitude: 7.8731, longitude: 80.6517 },
    category: 'Cultural Heritage',
    shortDescription: 'The grandest cave temple complex in Sri Lanka, boasting 153 Buddha statues beneath a sweeping rock ceiling.',
    description: 'Dambulla Cave Temple (Golden Temple of Dambulla) is an awe-inspiring sacred pilgrimage site dating back to the 1st century BCE. Located across five magnificent caves under an overhanging rock, it contains 153 Buddha statues and over 2,100 square meters of preserved Buddhist mural paintings.',
    images: [
      'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 17000,
    recommendedDuration: 1,
    bestMonths: ['January', 'February', 'March', 'June', 'July', 'August', 'September'],
    activities: [
      { name: 'Dambulla Cave Temples Exploration', description: 'Walk through 5 historic frescoed caverns atop the rock hill.', estimatedCost: 2000, duration: '2.5 hours' },
      { name: 'Golden Buddha Statue Viewing', description: 'Photograph the colossal 30-meter gilded Buddha at the base.', estimatedCost: 0, duration: '45 mins' },
    ],
    difficulty: 'Easy',
    popularityScore: 91,
    averageRating: 4.7,
    reviewCount: 230,
    entranceFee: { local: 0, foreign: 2000 },
    tags: ['Culture', 'History', 'Photography'],
    nearbyDestinations: [
      { name: 'Sigiriya', distanceKm: 24 },
      { name: 'Kandy', distanceKm: 72 },
      { name: 'Anuradhapura', distanceKm: 65 },
    ],
    transportationInfo: { trainAvailable: false, busAvailable: true, driveTimeFromColombo: '3.5 hours' },
  },
  {
    name: 'Kitulgala',
    slug: 'kitulgala',
    province: 'Sabaragamuwa',
    district: 'Kegalle',
    location: { latitude: 6.9934, longitude: 80.4138 },
    category: 'Nature & Adventure',
    shortDescription: 'Sri Lanka’s adventure capital: thrilling white-water rafting, waterfall abseiling, and lush rainforest.',
    description: 'Nestled along the Kelani River, Kitulgala is world-famous as the filming site of the Oscar-winning movie “The Bridge on the River Kwai”. Today, it attracts adventure seekers for grade 2 and 3 white-water rafting, canyoning, confidence jumps, waterfall abseiling, and bird watching in the primary rainforest.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 21000,
    recommendedDuration: 1,
    bestMonths: ['January', 'February', 'March', 'April', 'July', 'August', 'December'],
    activities: [
      { name: 'Kelani River White-Water Rafting', description: 'Conquer 5 major rapids and 4 minor rapids with certified river guides.', estimatedCost: 5500, duration: '2.5 hours' },
      { name: 'Waterfall Abseiling & Rock Slides', description: 'Rappel down natural rock faces into refreshing jungle pools.', estimatedCost: 6500, duration: '3 hours' },
      { name: 'Belilena Prehistoric Cave Visit', description: 'Discover cave archaeological remains of the 30,000-year-old Balangoda Man.', estimatedCost: 500, duration: '1.5 hours' },
    ],
    difficulty: 'Challenging',
    popularityScore: 87,
    averageRating: 4.7,
    reviewCount: 180,
    entranceFee: { local: 0, foreign: 0 },
    tags: ['Adventure', 'Nature', 'Waterfalls', 'Hiking'],
    nearbyDestinations: [
      { name: 'Colombo', distanceKm: 85 },
      { name: 'Kandy', distanceKm: 70 },
      { name: 'Nuwara Eliya', distanceKm: 75 },
    ],
    transportationInfo: { trainAvailable: false, busAvailable: true, driveTimeFromColombo: '2.5 hours' },
  },
  {
    name: 'Tangalle',
    slug: 'tangalle',
    province: 'Southern',
    district: 'Hambantota',
    location: { latitude: 6.0244, longitude: 80.7941 },
    category: 'Beaches & Coastal',
    shortDescription: 'Peaceful deep-south coastline with secluded coves, blowholes, and Rekawa turtle night watch.',
    description: 'Tangalle is the gateway to the wide open, unspoiled bays of Sri Lanka’s far south. Renowned for Goyambokka Beach, Mawella Bay, the natural ocean geyser at Hummanaya Blowhole, and midnight turtle nesting safaris on Rekawa Beach where five endangered species come ashore to lay eggs.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 22000,
    recommendedDuration: 2,
    bestMonths: ['November', 'December', 'January', 'February', 'March', 'April'],
    activities: [
      { name: 'Hummanaya Natural Ocean Blowhole', description: 'Witness sea sprays shooting 30 meters into the sky.', estimatedCost: 1000, duration: '1 hour' },
      { name: 'Rekawa Turtle Night Nesting Watch', description: 'Observe mother sea turtles laying clutches of eggs under the moonlight.', estimatedCost: 2500, duration: '3 hours' },
      { name: 'Goyambokka Cove Swimming', description: 'Swim in calm turquoise waters sheltered by rocky points.', estimatedCost: 0, duration: '3 hours' },
    ],
    difficulty: 'Easy',
    popularityScore: 89,
    averageRating: 4.8,
    reviewCount: 175,
    entranceFee: { local: 0, foreign: 0 },
    tags: ['Beaches', 'Wildlife', 'Nature', 'Photography'],
    nearbyDestinations: [
      { name: 'Mirissa', distanceKm: 42 },
      { name: 'Yala', distanceKm: 75 },
      { name: 'Udawalawe', distanceKm: 70 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '2.5 - 3 hours via expressway' },
  },
  {
    name: 'Negombo',
    slug: 'negombo',
    province: 'Western',
    district: 'Gampaha',
    location: { latitude: 7.2008, longitude: 79.8737 },
    category: 'Beaches & Coastal',
    shortDescription: 'Charming coastal town beside Bandaranaike Airport, celebrated for its lagoon, fish markets, and Dutch canals.',
    description: 'Located just 15 minutes from Bandaranaike International Airport, Negombo is the ideal first or last stop in Sri Lanka. Known affectionately as “Little Rome” for its vibrant Catholic churches, Negombo features bustling morning open-air fish markets (Lellama), calm lagoon boat tours, and relaxed coastal resorts.',
    images: [
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 18000,
    recommendedDuration: 1,
    bestMonths: ['January', 'February', 'March', 'April', 'November', 'December'],
    activities: [
      { name: 'Lellama Fish Market Dawn Tour', description: 'See catamaran fishermen unload tuna, crabs, and marlin at sunrise.', estimatedCost: 0, duration: '1.5 hours' },
      { name: 'Dutch Canal & Lagoon Boat Cruise', description: 'Glide along historic colonial waterways spotting kingfishers.', estimatedCost: 3500, duration: '2 hours' },
    ],
    difficulty: 'Easy',
    popularityScore: 88,
    averageRating: 4.5,
    reviewCount: 195,
    entranceFee: { local: 0, foreign: 0 },
    tags: ['Beaches', 'Food', 'Culture', 'Photography'],
    nearbyDestinations: [
      { name: 'Colombo', distanceKm: 35 },
      { name: 'Kandy', distanceKm: 105 },
      { name: 'Sigiriya', distanceKm: 145 },
    ],
    transportationInfo: { trainAvailable: true, busAvailable: true, driveTimeFromColombo: '45 mins' },
  },
  {
    name: 'Pasikudah',
    slug: 'pasikudah',
    province: 'Eastern',
    district: 'Batticaloa',
    location: { latitude: 7.9254, longitude: 81.5627 },
    category: 'Beaches & Coastal',
    shortDescription: 'World-famous calm bay with shallow crystal waters allowing bathers to walk hundreds of meters into the sea.',
    description: 'Pasikudah Bay is home to one of the longest stretches of shallow reef coastline in the world. The outer coral reef blocks ocean currents, creating a calm, crystal-clear, swimming pool-like lagoon where travelers can safely wade out up to 300 meters into the Indian Ocean.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 24000,
    recommendedDuration: 2,
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    activities: [
      { name: 'Shallow Bay Wade & Snorkeling', description: 'Wade out hundreds of meters in glass-clear waters over soft sand.', estimatedCost: 0, duration: '3 hours' },
      { name: 'Catamaran Sailing & Kayaking', description: 'Rent watercraft to explore the vibrant outer reef edge.', estimatedCost: 4000, duration: '2 hours' },
    ],
    difficulty: 'Easy',
    popularityScore: 87,
    averageRating: 4.7,
    reviewCount: 160,
    entranceFee: { local: 0, foreign: 0 },
    tags: ['Beaches', 'Photography', 'Nature'],
    nearbyDestinations: [
      { name: 'Trincomalee', distanceKm: 110 },
      { name: 'Polonnaruwa', distanceKm: 70 },
      { name: 'Arugam Bay', distanceKm: 140 },
    ],
    transportationInfo: { trainAvailable: false, busAvailable: true, driveTimeFromColombo: '6 hours' },
  },
  {
    name: 'Sinharaja Forest Reserve',
    slug: 'sinharaja',
    province: 'Sabaragamuwa',
    district: 'Ratnapura',
    location: { latitude: 6.4178, longitude: 80.4619 },
    category: 'Nature & Adventure',
    shortDescription: 'Sri Lanka’s last viable primary tropical rainforest, a UNESCO World Heritage site with rare endemic birds.',
    description: 'Sinharaja is Sri Lanka’s crown ecological treasure. More than 60% of the trees are endemic and many are considered rare. The reserve is world-renowned for its phenomenal mixed-species bird feeding flocks where up to 40 species travel together through the dense forest canopy, along with rare purple-faced langurs and colorful tree frogs.',
    images: [
      'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
    ],
    estimatedDailyCost: 20000,
    recommendedDuration: 1,
    bestMonths: ['December', 'January', 'February', 'March', 'August', 'September'],
    activities: [
      { name: 'Guided Primary Rainforest Trek', description: 'Trek with expert naturalist trackers identifying endemic flora and birds.', estimatedCost: 4500, duration: '4 hours' },
      { name: 'Natural Rainforest Waterfall Bath', description: 'Cool off in pristine jungle streams and crystalline pools.', estimatedCost: 0, duration: '1.5 hours' },
    ],
    difficulty: 'Moderate',
    popularityScore: 90,
    averageRating: 4.9,
    reviewCount: 185,
    entranceFee: { local: 100, foreign: 4500 },
    tags: ['Nature', 'Hiking', 'Wildlife', 'Photography', 'Adventure'],
    nearbyDestinations: [
      { name: 'Galle Fort', distanceKm: 75 },
      { name: 'Bentota', distanceKm: 85 },
      { name: 'Udawalawe', distanceKm: 70 },
    ],
    transportationInfo: { trainAvailable: false, busAvailable: true, driveTimeFromColombo: '3.5 hours' },
  },
];

const hotels = [
  {
    name: 'Heritance Kandalama',
    destination: 'Sigiriya',
    tier: 'Luxury',
    pricePerNight: 58000,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    amenities: ['Infinity Pool', 'Spa', 'Lake View', 'Fine Dining', 'Free WiFi'],
    contactPhone: '+94 66 555 5000',
  },
  {
    name: 'Sigiriya Village Hotel',
    destination: 'Sigiriya',
    tier: 'Moderate',
    pricePerNight: 22000,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
    amenities: ['Swimming Pool', 'Garden View', 'Restaurant', 'Free WiFi'],
    contactPhone: '+94 66 228 6803',
  },
  {
    name: 'Lion Rock Guest House',
    destination: 'Sigiriya',
    tier: 'Budget',
    pricePerNight: 7500,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
    amenities: ['Free WiFi', 'Breakfast Included', 'Bicycle Rental'],
    contactPhone: '+94 77 123 4567',
  },
  {
    name: '98 Acres Resort & Spa',
    destination: 'Ella',
    tier: 'Luxury',
    pricePerNight: 65000,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    amenities: ['Helipad', 'Infinity Pool', 'Spa', 'Tea Estate View', 'Bar'],
    contactPhone: '+94 57 205 0050',
  },
  {
    name: 'Ella Mountain View Resort',
    destination: 'Ella',
    tier: 'Moderate',
    pricePerNight: 18000,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
    amenities: ['Balcony View', 'Restaurant', 'Free WiFi', 'Tour Desk'],
    contactPhone: '+94 57 222 8888',
  },
  {
    name: 'Ella Backpackers Hostel',
    destination: 'Ella',
    tier: 'Budget',
    pricePerNight: 5500,
    rating: 4.3,
    image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
    amenities: ['Free WiFi', 'Lounge', 'Shared Kitchen', 'Terrace'],
    contactPhone: '+94 71 555 1234',
  },
  {
    name: 'The Grand Hotel Nuwara Eliya',
    destination: 'Nuwara Eliya',
    tier: 'Luxury',
    pricePerNight: 62000,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    amenities: ['Heated Pool', 'High Tea Lounge', 'Billiards Room', 'Spa'],
    contactPhone: '+94 52 222 2881',
  },
  {
    name: 'Amangalla',
    destination: 'Galle Fort',
    tier: 'Luxury',
    pricePerNight: 95000,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    amenities: ['Historic Suites', 'Hydrotherapy Pool', 'Ayurvedic Spa', 'Library'],
    contactPhone: '+94 91 223 3388',
  },
  {
    name: 'Cinnamon Grand Colombo',
    destination: 'Colombo',
    tier: 'Luxury',
    pricePerNight: 48000,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    amenities: ['14 Restaurants', '2 Pools', 'Fitness Center', 'Spa'],
    contactPhone: '+94 11 243 7437',
  },
];

module.exports = { categories, destinations, hotels };
